### ISSUE TITLE
Problem with execution (gperftools)

### ISSUE THREAD

**Issue by DanDits** [alexnoe/VieCut#1] opened 2019-09-04 10:39 UTC
Hi I cloned and built it on my system (archlinux) which worked out fine. I only had to adjust your two CMakeLists.txt files since on my machine the libtcmalloc_and_profiler.so dependency was found under /usr/lib/libtcmalloc_and_profiler.so directly and not in at /usr/lib/x86_64-linux-gnu/libtcmalloc_and_profiler.so.
But on attempting to execute the suggested command:
./build/mincut -q bqueue -i 3 -p 2 graphs/small.metis 

I get an error:
Check failed: !internal_init_start_has_run: Heap-check constructor called twice.  Perhaps you both linked in the heap checker, and also used LD_PRELOAD to load it?
Aborted (core dumped)
This error seems to come from gperftools (https://github.com/couchbase/gperftools/blob/master/src/heap-checker.cc).

Note that the tests run successfully using ctest -V
100% tests passed, 0 tests failed out of 17

Total Test time (real) =   5.37 sec

**Comment by alexnoe** [comment] 2019-09-04 13:50
Thanks for the issue!

At least the first issue should be fixed now. Can you please check whether the second is also fixed? I did things that I hope will fix it, but I can't reproduce the error. With g++-7, g++-8, g++-9 and clang++-6.0 I don't get the issue you described.

**Comment by alexnoe** [comment] 2019-09-11 13:54
I assume this is fixed, as the including of gperftools was cleaned up.

**Closed by alexnoe** 2019-09-11 13:54 UTC
